App/App/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('checkout/<int:car_id>', views.checkout, name = "checkout"),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('details/<int:car_id>', views.details, name = 'details'),
    path('high_low/', views.high_low, name = 'high_low'),
    path('low_high/', views.low_high, name='low_high')
]

App/main/models.py
from django.db import models


class Car(models.Model):
    car_name = models.CharField('car_name', max_length=100)
    car_photo = models.ImageField('car_img', upload_to='uploads/')
    car_desc = models.TextField('car_description')
    car_price = models.IntegerField('car_price')


# Create your models here.
class Request(models.Model):
    user_name = models.CharField('user_name', max_length=100)
    user_phone_number = models.CharField('user_phone_number', max_length=100)
    user_car = models.ForeignKey(Car, on_delete=models.CASCADE)

App/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

App/main/views.py
from django.shortcuts import render, redirect
from .models import Car, Request
from django.contrib.auth import authenticate, login, logout
from .forms import SignupForm, LoginForm


# Create your views here.
def index(request):
    all_cars = Car.objects.all()
    return render(request, 'main/index.html', {'all_cars': all_cars})


def checkout(request, car_id):
    if request.method == 'POST':
        return render(request, 'main/success.html')
    else:
        return render(request, 'main/checkout.html', {'car_id': car_id})


# signup page
def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:login')
    else:
        form = SignupForm()
    return render(request, 'main/signup.html', {'form': form})


# login.css page
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('main:index')
    else:
        form = LoginForm()
    return render(request, 'main/login.html', {'form': form})


# logout page
def user_logout(request):
    logout(request)
    return redirect('main:login')


def details(request, car_id):
    car = Car.objects.get(id=car_id)
    return render(request, 'main/details.html', {'car': car})


def low_high(request):
    all_cars = Car.objects.order_by('car_price')
    return render(request, 'main/index.html', {'all_cars': all_cars})


def high_low(request):
    all_cars = Car.objects.order_by('-car_price')
    return render(request, 'main/index.html', {'all_cars': all_cars})

App/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css' %}">

    {% block style %}{% endblock %}
</head>
<body>
    <header id = "header">
           <div class="container">
               <div class="header">
                    <div class="top_header">
                        <div class="phrase">
                            <h1>AutoSale</h1>
                        </div>
                        <a href="{% url 'main:index' %}" class = "logo"><img src="{% static 'main/img/logo/logo.jpg' %}" alt="logo"></a>
                        <div class="right_side">
                            {% if request.user.is_authenticated %}
                                {{ request.user.username }}
                                <a href="{% url 'main:logout' %}">Logout</a>
                            {% else %}
                                <a href="{% url 'main:login' %}">Login</a>
                                <a href="{% url 'main:signup' %}">Signup</a>
                            {% endif %}
                        </div>
                        <div class="header_burger"><span></span></div>
                    </div>
                   <div class="bottom_header">
                        <nav class = "navbar">
                            <ul class="nav_list">
                                <li class="list_item"><a href="{% url 'main:index' %}">Home</a></li>
                                <li class="list_item"><a href="#section2">About us</a></li>
                                <li class="list_item"><a href="#section4">Reviews</a></li>
                            </ul>
                        </nav>
                    </div>
               </div>
           </div>
    </header>
    <div class="container">
        {% block content %}
            content
        {% endblock %}
    </div>
    <footer id = "footer">
        <div class="container">
            <div class="footer_social">
                <a href="#"><img src="{% static 'main/img/icons/instagram.png' %}" alt="img"></a>
                <a href="#"><img src="{% static 'main/img/icons/whatsapp.png' %}" alt="img"></a>
            </div>
            <div class="footer_copyright">
                Copyright © 2020–2023 auto.com All rights reserved.
            </div>
        </div>
    </footer>
    <script src = "{% static 'main/js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>
</html>

App/templates/main/checkout.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'main/css/checkout.css' %}">{% endblock %}

{% block content %}
<form class="checkout" method="POST" action = '{% url "main:checkout" car_id %}'>
  {% csrf_token %}
            <div class="row">
            <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" placeholder="John M. Doe">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email" placeholder="john@example.com">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="New York">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container">
              <i class="fa fa-cc-visa" style="color:navy;"></i>
              <i class="fa fa-cc-amex" style="color:blue;"></i>
              <i class="fa fa-cc-mastercard" style="color:red;"></i>
              <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe">
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="September">

            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>

        </div>
        <label>
          <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
        </label>
        <input type="submit" value="Continue to checkout" class="btn">
        </form>
{% endblock %}

App/templates/main/details.html
{% extends 'main/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/css/details.css' %}">{% endblock %}

{% block content %}
    <div class="car_details">
        <div class="left__side">
            <h2 class="car_name">{{car.car_name}}</h2>
            <img src="/media/{{car.car_photo}}" alt="img" class="car_img">
            <p class="car_price">{{car.car_price}}P</p>
            <a class="leave_request" href = "{% url 'main:checkout' car.id %}">Request</a>
        </div>
        <div class="right__side">
            <p class="text">{{ car.car_desc }}</p>
        </div>
    </div>

{% endblock %}

App/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'main/css/index.css' %}">
{% endblock %}
{% block content %}
    <section id="section1">
        <div class="filter">
        <a href="{% url 'main:high_low' %}" class="high_low">Сначало дорогие</a>
        <a href="{% url 'main:low_high' %}" class="low_high">Сначало дешевые</a>
    </div>
    <div class="all_cars">
        {% for car in all_cars %}
            <div class="car">
                <img src="/media/{{car.car_photo}}" alt="img" class="car_img">
                <h2 class="car_name">{{car.car_name}}</h2>
                <p class="car_price">{{car.car_price}}P</p>
                <a class="leave_request" href = "{% url 'main:checkout' car.id %}">Request</a>
                <a href="{% url 'main:details' car.id %}" class="details">Details</a>
                <div class="car_cover"></div>
            </div>
        {% endfor %}
    </div>
    </section>
    <section id="section2">
                <div class="container">
                    <div class="about_us">
                        <div class="about_us_text">
                            <h2>About us</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium aut consectetur consequuntur cum deserunt doloribus eaque eius eum, nemo numquam odit, officiis pariatur quae recusandae sunt ullam ut vel vitae. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab accusamus alias, aperiam blanditiis consequatur dignissimos doloremque dolores doloribus eligendi et illo ipsam iure mollitia officia perspiciatis quo, quod vel voluptatibus.</p>
                        </div>
                        <div class="about_us_carousel">
                            <div id="carouselExampleFade" class="carousel slide carousel-fade">
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <img src="https://cdn.motor1.com/images/mgl/ZnmO23/s3/future-cars-2023-2026.jpg" class="d-block w-100" alt="img">
                                    </div>
                                    <div class="carousel-item active">
                                        <img src="https://www.hdwallpapers.in/download/2024_lamborghini_revuelto_car_4k_5k_hd_cars-1280x720.jpg" class="d-block w-100" alt="img">
                                    </div>
                                </div>
                                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Previous</span>
                                </button>
                                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Next</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section id="section4">
                <div class="container">
                    <div class="outerdiv">

                        <div class="innerdiv">
                          <!-- div1 -->
                          <div class="div1 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name">Faranak h_n</p>
                              </div>
                            </div>
                            <div class="review">
                            <p>“Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem neque pariatur quos suscipit. Delectus eius error ex facilis ipsum laboriosam laborum porro quam quis, quisquam quod repudiandae suscipit temporibus ullam.”</p>
                            </div>
                          </div>
                          <!-- div2 -->
                          <div class="div2 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name">Sally Elazab</p>
                              </div>
                            </div>
                            <div class="review">
                            <p>“Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem neque pariatur quos suscipit. Delectus eius error ex facilis ipsum laboriosam laborum porro quam quis, quisquam quod repudiandae suscipit temporibus ullam.”</p>
                            </div>
                          </div>
                          <!-- div3 -->
                          <div class="div3 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name dark">Ralph Boyz</p>
                              </div>
                            </div>
                            <div class="review dark">
                            <p>“Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem neque pariatur quos suscipit. Delectus eius error ex facilis ipsum laboriosam laborum porro quam quis, quisquam quod repudiandae suscipit temporibus ullam.”</p>
                            </div>
                          </div>
                          <!-- div4 -->
                          <div class="div4 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name dark">Lena Sami</p>
                              </div>
                            </div>
                            <div class="review dark">
                            <p>“Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem neque pariatur quos suscipit. Delectus eius error ex facilis ipsum laboriosam laborum porro quam quis, quisquam quod repudiandae suscipit temporibus ullam.”</p>
                            </div>
                          </div>
                          <!-- div5 -->
                          <div class="div5 eachdiv">
                            <div class="userdetails">
                              <div class="detbox">
                                <p class="name">Nisreen Sherbatji</p>
                              </div>
                            </div>
                            <div class="review">
                            <p>“Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem neque pariatur quos suscipit. Delectus eius error ex facilis ipsum laboriosam laborum porro quam quis, quisquam quod repudiandae suscipit temporibus ullam.”</p>

                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </section>

{% endblock %}

App/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'main/css/login.css' %}">{% endblock %}
{% block content %}

<form method="POST">
    <h1>Login</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
    <a href="{% url 'main:signup' %}">Dont have Account Create</a>
</form>
{% endblock %}
<h1>Welcome!</h1>

App/templates/main/signup.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'main/css/signup.css' %}">{% endblock %}
{% block content %}

<form method="POST">
    <h1>Signup</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Signup</button>
    <a href="{% url 'main:login' %}">Already have account?</a>
</form>

{% endblock %}

App/templates/main/success.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'main/css/success.css' %}">{% endblock %}
{% block content %}
<h1>Order is successfully placed</h1>
{% endblock %}